# Generated by Django 4.2.3 on 2023-11-03 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('from_year', models.DateField()),
                ('to_year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('description', models.TextField()),
                ('parent_id', models.IntegerField()),
                ('period_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Arch_app.period')),
            ],
        ),
        migrations.CreateModel(
            name='StylePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_to_picture', models.URLField(null=True)),
                ('style_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Arch_app.style')),
            ],
        ),
    ]
