# Generated by Django 4.2.6 on 2023-11-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arch_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='style',
            name='parent_id',
            field=models.IntegerField(null=True),
        ),
    ]
