# Generated by Django 4.2.6 on 2024-02-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arch_app', '0002_alter_style_description_alter_style_parent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='from_year',
        ),
        migrations.RemoveField(
            model_name='period',
            name='to_year',
        ),
        migrations.RemoveField(
            model_name='style',
            name='description',
        ),
        migrations.AddField(
            model_name='style',
            name='basic_decorative_elements',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='style',
            name='distinctive_features',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='style',
            name='example_name',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='style',
            name='slug',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='style',
            name='was_built',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='style',
            name='name',
            field=models.TextField(max_length=50),
        ),
    ]
