# Generated by Django 4.2.6 on 2024-02-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arch_app', '0003_remove_period_from_year_remove_period_to_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='time',
            field=models.TextField(default=''),
        ),
    ]
